languageCode = "en"
languageName = "English"
weight = 1
title = "Yorkshire Geeek"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "just a nerd lost in the world of geek"

[author]
name = "Richard Thomas"
image = "PXL_20240616_122019749.jpg "
headline = "YorkshireGeek"
bio = "add me later"
